newMatatus/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^ratings/', include('ratings.urls', namespace="ratings")),
    url(r'^admin/', include(admin.site.urls)),
)

newMatatus/mysite/ratings/urls.py
from django.conf.urls import patterns, url

from ratings import views

urlpatterns = patterns('',
    # ex: /ratings/
    url(r'^$', views.index, name='index'),
    url(r'about-us', views.about_us, name='about_us'),
    url(r'rate_form', views.rate_form, name='rate_form'),    
    url(r'rate', views.rate, name='rate'),        
)

newMatatus/mysite/ratings/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone


class AuthGroup(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    group = models.ForeignKey(AuthGroup)
    permission = models.ForeignKey('AuthPermission')

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'


class AuthPermission(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    name = models.CharField(max_length=50)
    content_type = models.ForeignKey('DjangoContentType')
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'


class AuthUser(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField()
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=75)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    user = models.ForeignKey(AuthUser)
    group = models.ForeignKey(AuthGroup)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'


class AuthUserUserPermissions(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    user = models.ForeignKey(AuthUser)
    permission = models.ForeignKey(AuthPermission)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'


class DjangoAdminLog(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.IntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', blank=True, null=True)
    user = models.ForeignKey(AuthUser)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    name = models.CharField(max_length=100)
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'


class DjangoMigrations(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Matatus(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    ratings = models.CharField(db_column='Ratings', max_length=45, blank=True)  # Field name made lowercase.
    number_of_comments = models.CharField(max_length=45, blank=True)
    plate_number = models.CharField(max_length=45, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'matatus'


class Reviews(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    route_shot_name = models.CharField(max_length=45, blank=True)
    id_user = models.CharField(max_length=45, blank=True)
    plate_number = models.CharField(max_length=45, blank=True)
    rating = models.CharField(db_column='Rating', max_length=45, blank=True)  # Field name made lowercase.
    comments = models.CharField(max_length=2000, blank=True)
    date = models.DateTimeField(blank=True, null=True)
    comment_number = models.CharField(max_length=45, blank=True)
    comment_title = models.CharField(max_length=1000, blank=True)
    username = models.CharField(max_length=45, blank=True)

    class Meta:
        managed = False
        db_table = 'reviews'


class Routes(models.Model):
    route_id = models.CharField(max_length=11, blank=True)
    agency_id = models.CharField(max_length=3, blank=True)
    route_shot_name = models.CharField(max_length=45, blank=True)
    route_long_name = models.CharField(max_length=45, blank=True)
    route_desc = models.CharField(max_length=45, blank=True)
    route_type = models.CharField(max_length=45, blank=True)
    route_url = models.CharField(max_length=45, blank=True)
    route_color = models.CharField(max_length=45, blank=True)
    route_text_color = models.CharField(max_length=45, blank=True)
    id = models.IntegerField(primary_key=True)  # AutoField?

    class Meta:
        managed = False
        db_table = 'routes'


class Stops(models.Model):
    stop_id = models.CharField(primary_key=True, max_length=7)
    stop_code = models.CharField(max_length=45, blank=True)
    stop_name = models.CharField(max_length=45, blank=True)
    stop_lat = models.DecimalField(max_digits=8, decimal_places=6, blank=True, null=True)
    stop_lon = models.DecimalField(max_digits=8, decimal_places=6, blank=True, null=True)
    zone_id = models.CharField(max_length=45, blank=True)
    stop_url = models.CharField(max_length=45, blank=True)
    location_type = models.CharField(max_length=45, blank=True)
    parent_station = models.CharField(max_length=45, blank=True)

    class Meta:
        managed = False
        db_table = 'stops'


class Users(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    username = models.CharField(unique=True, max_length=255)
    hash = models.CharField(max_length=255)
    email = models.CharField(max_length=45, blank=True)
    phone = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True)

    class Meta:
        managed = False
        db_table = 'users'

newMatatus/mysite/ratings/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from datetime import datetime

from ratings.models import Reviews, Routes

def index(request):
    latest_reviews_list = Reviews.objects.order_by('-id')[:5]
    context = {'latest_reviews_list': latest_reviews_list}
    return render(request, 'ratings/index.html', context)

#def detail(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/detail.html', {'question': question})

def base(request):
    return render(request, 'ratings/base.html')

def about_us(request):
    return render(request, 'ratings/about-us.html')

def rate_form(request):
    routes_list = Routes.objects.order_by('id')
    blah = {'routes_list': routes_list}    
    return render(request, 'ratings/rate_matatu_form.html', blah)

def rate(request):
	b = Reviews(route_shot_name=request.POST['route_shot_name'], id_user='2', plate_number=request.POST['plate_number'], rating=request.POST['Rating'], comments=request.POST['comments'], date=datetime.now(), comment_number='2', comment_title=request.POST['comment_title'], username='sloan.holzman')
	b.save()
	return HttpResponseRedirect(reverse('ratings:index'))

newMatatus/mysite/ratings/templates/ratings/base.html
<!DOCTYPE html>
<html>
	<head>
	{% load staticfiles %}

	{% block stylesheets %}
		<link href="{% static 'ratings/css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/bootstrap-select.min.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/bootstrap-select.css' %}' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/bootstrap-select.css.map' %}" rel="stylesheet">        
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		<link href="{% static 'ratings/css/animate.min.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/prettyPhoto.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/main.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/smart_matatus.css' %}" rel="stylesheet">    
		<link href="{% static 'ratings/css/responsive.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/jquery.dataTables_themeroller.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/jquery.dataTables.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/jquery.dataTables.min.css' %}" rel="stylesheet">
		<!--be careful...this stuff might screw up the styling-->
		<link href="{% static 'ratings/css/example.minimal.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/example.wink.css' %}" rel="stylesheet">
		<link href="{% static 'ratings/css/star-rating.min.css' %}" rel="stylesheet">
	{% endblock %}
	{% block javascript %}
	    <script src="{% static 'ratings/js/jquery.js' %}"></script>
	    <script src="{% static 'ratings/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'ratings/js/jquery.prettyPhoto.js' %}"></script>
	    <script src="{% static 'ratings/js/jquery.isotope.min.js' %}"></script>
	    <script src="{% static 'ratings/js/main.js' %}"></script>
	    <script src="{% static 'ratings/js/wow.min.js' %}"></script>
	    <script src="{% static 'ratings/js/smart_matatus.js' %}"></script>
	    <script src="{% static 'ratings/js/bootstrap-select.js' %}"></script>
	    <script src="{% static 'ratings/js/bootstrap-select.min.js' %}"></script>
	    <script src="{% static 'ratings/js/bootstrap-select.js.map"></script>
	    <script src="{% static 'ratings/js/jquery.dataTables.js' %}"></script>
	    <script src="{% static 'ratings/js/jquery.dataTables.min.js' %}"></script>
	    <script src="{% static 'ratings/js/hideShowPassword.js' %}"></script>   
	    <script src="{% static 'ratings/js/hideShowPassword.min.js' %}"></script>
	    <script src="{% static 'ratings/js/star-rating.min.js' %}"></script>
	{% endblock %}
	</head>

	<body>
	    <header id="header">
	        <div class="top-bar">
	            <div class="container">
	                <div class="row">
	                    <div class="col-sm-6 col-xs-4">
	                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  +19178808790</p></div>
	                    </div>
	                    <div class="col-sm-6 col-xs-8">
	                       <div class="social">
	                            <ul class="new_login">
	                                <li><a href="../public/logout.php">Logout</a></li>
	                            </ul>
	                            <ul class="social-share">
	                                <li><a href="../public/construction.php"><i class="fa fa-facebook"></i></a></li>
	                                <li><a href="../public/construction.php"><i class="fa fa-twitter"></i></a></li>
	                            </ul>
	                            <div class="search">
	                                <form role="form">
	                                    <input type="text" class="search-form" autocomplete="on" placeholder="Search">
	                                    <i class="fa fa-search"></i>
	                                </form>
	                           </div>
	                       </div>
	                    </div>
	                </div>
	            </div><!--/.container-->
	        </div><!--/.top-bar-->

	        <nav class="navbar navbar-inverse" role="banner">
	            <div class="container">
	                <div class="navbar-header">
	                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	                        <span class="sr-only">Toggle navigation</span>
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                    </button>
	                    <a class="navbar-brand" href="{% url 'ratings:index' %}"><img src="{% static 'ratings/images/SmartMatatusLogo.jpg' %}" alt="logo"></a>
	                </div>
					
	                <div class="collapse navbar-collapse navbar-right">
	                    <ul class="nav navbar-nav">
	                        <li class="active"><a href="../index.php">Home</a></li>
	                        <li><a href="{% url 'ratings:about_us' %}">About Us</a></li>
	                        <li class="dropdown">
	                            <a href="../public/rate_matatu.php" class="dropdown-toggle" data-toggle="dropdown">Matatu Rating<i class="fa fa-angle-down"></i></a>
	                            <ul class="dropdown-menu">
	                                <li><a href="../public/select_route.php">Search Ratings</a></li>
	                                <li><a href="../public/rate_matatu.php">Rate a Matatu</a></li>
	                            </ul>
	                        </li>
	                        <li class="dropdown">
	                            <a href="../public/route_maps.php" class="dropdown-toggle" data-toggle="dropdown">Directions<i class="fa fa-angle-down"></i></a>
	                            <ul class="dropdown-menu">
	                                <li><a href="../public/route_maps.php">Maps</a></li>
	                                <li><a href="../public/directions.php">Directions</a></li>
	                                <li><a href="../public/routes.php">Routes</a></li>
	                            </ul>
	                        </li>
	                        <li class="dropdown">
	                            <a href="../public/construction.php" class="dropdown-toggle" data-toggle="dropdown">GPS Tracking<i class="fa fa-angle-down"></i></a>
	                            <ul class="dropdown-menu">
	                                <li><a href="../public/construction.php">Search</a></li>
	                                <li><a href="../public/construction.php">Favorite Routes</a></li>
	                            </ul>
	                        </li>
	                    </ul>
	                </div>
	            </div><!--/.container-->
	        </nav><!--/nav-->
			
	    </header><!--/header-->
	{% block content %}

		<section id="blog" class="container">
		    <div class="center">
		        <h2>Sorry, No Ratings!</h2>
		        <p>
					{% if latest_reviews_list %}
					    <ul>
					    {% for reviews in latest_reviews_list %}
					        <li>{{ reviews.plate_number }}</li>
					    {% endfor %}
					    </ul>
					{% else %}
					    <p>No reviews are available.</p>
					{% endif %}
		        </p>
		        <a class="btn btn-primary" href="../public/welcome.php">GO BACK TO THE HOMEPAGE</a>
		    </div>
		</section>

	{% endblock %}
	    <section id="bottom">

	    </section><!--/#bottom-->
	    <footer id="footer" class="midnight-blue">
	        <div class="container">
	            <div class="row">
	                <div class="col-sm-6">
	                    Sloan Holzman, Public Entrepreneurship.
	                </div>
	                <div class="col-sm-6">
	                    <ul class="pull-right">
	                        <li><a href="../public/welcome.php">Home</a></li>
	                        <li><a href="../public/about-us.php">About Us</a></li>
	                    </ul>
	                </div>
	            </div>
	        </div>
	    </footer><!--/#footer-->
	</body>
</html>

newMatatus/mysite/ratings/templates/ratings/details.html
<h1>Plate Number: {{ reviews.plate_number }}</h1>
<ul>
{% for review in reviews %}
    <li>{{ reviews.plate_number }}</li>
    <li>{{ reviews.route_shot_name }}</li>
    <li>{{ reviews.rating }}</li>
    <li>{{ reviews.comment_title }}</li>
    <li>{{ reviews.choice_text }}</li>
    <li>{{ reviews.choice_text }}</li>
{% endfor %}
</ul>

newMatatus/mysite/ratings/templates/ratings/index.html
{% extends 'ratings/base.html' %}
 
{% block content %}
		<section id="blog" class="container">
		    <div class="center">
		        <h2>Sorry, No Ratings!</h2>
		        <p>
					{% if latest_reviews_list %}
					    <ul>
					    {% for reviews in latest_reviews_list %}
					        <li>{{ reviews.plate_number }}</li>
					    {% endfor %}
					    </ul>
					{% else %}
					    <p>No reviews are available.</p>
					{% endif %}
		        </p>
		        <a class="btn btn-primary" href="../public/welcome.php">GO BACK TO THE HOMEPAGE</a>
		    </div>
		</section>
{% endblock %}

newMatatus/mysite/ratings/templates/ratings/rate_matatu_form.html
{% extends 'ratings/base.html' %}
{% load staticfiles %} 
{% block content %}
<title>Rate A Matatu</title>
<section id="blog" class="container">
    <div class="center">
        <h2>Rate Your Matatu</h2>
    </div>
    <div id="contact-page clearfix">
        <form action="{% url 'ratings:rate' %}" method="post" name="ratingsForm">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>License Plate Number: </label>
                        <input type="text" class="form-control" required="required" placeholder="e.g. 5791CD" name="plate_number">
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>Route: </label>
                        <br>
                        <select class="selectpicker" name="route_shot_name" required="required">
                            {% for routes in routes_list %}
                                <option>{{ routes.route_shot_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label>Rating: </label>
                        <br>
                        <input id="input-21e" value="0" type="number" name="Rating" required="required" class="rating" min=0 max=5 step=0.5 data-size="xs" >
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">                        
                    <div class="form-group">
                        <label>Comment Headline: </label>
                        <textarea name="comment_title" id="message" required="required" placeholder="e.g. Best Matatu Ride Ever!" class="form-control" rows="1"></textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">                        
                    <div class="form-group">
                        <label>Comments: </label>
                        <textarea name="comments" id="message" required="required" placeholder="e.g. The driver was very courteous.  He obeyed all the rules of the road.  AND HE PLAYED GREAT MUSIC!" class="form-control" rows="8"></textarea>
                    </div>
                </div>
            </div>
            <div class "row">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg" required="required">Submit Review</button>
                </div>
            </div>
        </form>
    </div>   
</section>

{% endblock %}